/**
 * The `replay` tool's parameters, and the arguments type every action handler takes.
 */
import { z } from 'zod';

export const replaySchema = z.object({
  action: z.enum([
    'history', 'create', 'list', 'get', 'delete',
    'export', 'load', 'listSaved', 'deleteSaved',
    'run', 'runAll', 'step', 'finish', 'insert', 'addCheck', 'declare', 'status', 'cancel',
    'repeat', 'runFromLog',
    'recordInteraction'
  ]),
  limit: z.number().optional().describe('Max items (default:50)'),
  name: z.string().optional(),
  description: z.string().optional(),
  expectedOutcome: z.string().optional(),
  startUrl: z.string().optional().describe('create: sequence start URL. run: replace the stored startUrl for this run only (e.g. a freshly minted link)'),
  envFile: z.string().optional().describe("run/runAll: a KEY=value file supplying the {{env:NAME}} tokens this run resolves. A relative path resolves against the project directory (the one holding .devharness); absolute is used as-is. Its values WIN over the server's own environment, and the server's environment is never modified - two runs may name different files. A missing file, or a line that is neither blank, a # comment, nor NAME=value, fails before anything runs. Keeps a credential out of the sequence file and out of this call, and changing it needs no client restart"),
  baseUrl: z.string().optional().describe('run/runAll: retarget at another deployment — every absolute URL (startUrl, command params, a declared connection\u2019s launch url) keeps its path/query but takes this origin, in the sequence itself and in every sequence it reaches through a check that runs one or a forEach. On runAll it applies to every sequence in the suite. Not preserved across a mid-run pause/step resume'),
  indices: z.array(z.number()).optional().describe('Command indices'),
  lines: z.array(z.number()).optional().describe('Log line numbers'),
  sequenceId: z.string().optional(),
  runId: z.string().optional().describe('status/cancel: address a specific background run by the id that run returned'),
  bench: z.boolean().optional().describe('run: play in the bench open on connectionReason, as its Replay button does, so it shows there'),
  wait: z.boolean().optional().describe('run: block until the run completes and return the full result (pre-0.7 behaviour). Default false: return a runId immediately and execute in the background'),
  global: z.boolean().optional().describe('Use ~/.devharness/'),
  format: z.enum(['sequence', 'playwright', 'puppeteer']).optional(),
  filename: z.string().optional(),
  intoHistory: z.boolean().optional(),
  connectionReason: z.string().optional(),
  requiredConnections: z.array(z.object({
    reference: z.string().describe('Reference the steps use, e.g. "duo-member-two"'),
    profile: z.string().optional().describe('Named persistent Chrome profile to come up on (the profile connection launch takes). The durable identity: its storage survives between runs, so a device enrolled once stays enrolled'),
    url: z.string().optional().describe("Opened on launch (defaults to the sequence's startUrl)"),
    role: z.string().optional().describe('Why this browser exists, shown in the run summary'),
    forceNewInstance: z.boolean().optional().describe('A distinct process rather than a tab. Default true, but false when profile is set - only one live Chrome may hold a profile'),
  }).strict()).optional().describe('declare: the browsers this sequence needs. Replaces the whole list; [] clears it'),
  tags: z.array(z.string()).optional().describe("declare: what kind of sequence this is, e.g. ['ui'] or ['contract','slow'] - replaces the whole list, [] clears it. runAll: run only sequences carrying at least one of these tags; the summary reports the split either way"),
  requiredSockets: z.array(z.string()).optional().describe("declare: URL substrings of the WebSockets this sequence's assertions ride on, e.g. ['/api/sync/socket']. Match the app's own path, not the origin, so it survives baseUrl. Replaces the whole list; [] clears it"),
  connections: z.record(z.string()).optional().describe("run: rebind a multi-connection sequence's recorded references onto this session - { \"<recorded reference>\": \"<reference here>\" }. Only needed when steps carry their own connectionReason (replay({action:'get', outputFormat:'commands'}) shows which)"),
  record: z.boolean().optional(),
  variables: z.record(z.string()).optional().describe("run/runAll: replace the text of recorded input-type steps. Keys are BUILT from the selector - var_<0-based step index>_<selector, non-alphanumerics replaced by _> - so '#password' at step 3 is 'var_3__password', two underscores; read them off `get` or off the prompt a run returns rather than composing them. A key naming no typed-text step is rejected (runAll checks against the whole suite's union). Reaches sequences a check's run or a forEach nests into. For a credential prefer {{env:NAME}} in the step itself, which keeps the value out of the sequence file and out of this call; an explicit value here still wins over the environment"),
  stepTimeout: z.number().optional().describe('Per-step ms (default 30000). A step exceeding min(stepTimeout, remaining totalTimeout) fails the run at that step. wait steps are exempt (own timeoutMs) but still capped by totalTimeout'),
  totalTimeout: z.number().optional().describe('Total ms'),
  startFrom: z.number().optional().describe('Start step (1-indexed)'),
  stepTo: z.number().optional().describe('Pause after step'),
  stepCount: z.number().optional().describe('Steps to run'),
  insertIndices: z.array(z.number()).optional(),
  insertAfterStep: z.number().optional(),
  check: z.record(z.any()).optional().describe("addCheck: the check step's parameters, as the check tool takes them - what it reads (selector + condition, value + operator + right, url, cookie, localStorage, indexedDB, expression, or afterMs alone for a timer), withinMs to read again until it holds, and holds/fails: 'continue' | 'stop' | { run: '<sequence>', resumeAt }. resumeAt is a 0-based step of THIS sequence as it stands before the check goes in, forward only. A guard: { selector: '.cookie-banner', condition: 'present', holds: { run: 'dismiss-cookies' }, fails: 'continue' }"),
  comment: z.string().optional().describe('addCheck: note stored on the step'),
  overwrite: z.boolean().optional(),
  newName: z.string().optional(),
  showOverlay: z.boolean().optional(),
  closeTabOnDone: z.boolean().optional()
    .describe('recordInteraction: whether finishing closes the tab (default:true). False leaves a tab the person was already working in'),
  simplifyEvents: z.boolean().optional().describe('recordInteraction: collapse noisy raw events (default:true)'),
  includeHovers: z.boolean().optional().describe('recordInteraction: keep mousemove steps (default:false)'),
  outputFormat: z.enum(['events', 'commands', 'review', 'puppeteer', 'playwright']).optional()
    .describe('get: commands|playwright|puppeteer. recordInteraction: events|commands|review (JSON dump, or a human-readable event walkthrough, appended to the summary)'),
  preferCoordinates: z.boolean().optional().describe('recordInteraction: emit x,y clicks instead of selectors (default:false)'),
  preferSelectors: z.boolean().optional().describe('recordInteraction: emit selector clicks even for canvas; wins over preferCoordinates (default:false)'),
  issueId: z.number().optional(),
  issueType: z.enum(['bug', 'feature']).optional(),
  issueTitle: z.string().optional(),
  showReplayOverlay: z.boolean().optional(),
  showAll: z.boolean().optional().describe('Show all sequences including completed/fixed issues'),
  requireSockets: z.boolean().optional().describe("run/runAll: fail the run if any WebSocket CLOSED or hit frame errors while it executed. Diffed against the start, so a socket already down is not blamed on this sequence, and it catches a drop that recovered before the last step - which a final assertion cannot see. Usually unnecessary: a sequence that sets `requiredSockets` (URL substrings of the sockets its assertions ride on) is checked without asking, and that check also fails when a declared socket is missing or never opened, which no closure count can detect"),
  strict: z.enum(['errors', 'warnings']).optional().describe("run/runAll: fail the run when it PRODUCES console output - 'errors' fails on new console errors, 'warnings' also fails on new warnings. Counted per connection and diffed against the start of the run, so pre-existing noise is not blamed on this sequence. A sequence can be functionally correct and still be logging; strict is how you separate those questions"),
  folder: z.string().optional().describe("runAll: sequences subfolder to run, relative to the sequences dir (e.g. 'spine'). Omit to run every sequence outside folders whose name starts with '_'. The whole tree is always LOADED first so name references (a check's run, a forEach's do) resolve wherever the helper lives"),
  continueOnFailure: z.boolean().optional().describe('runAll: keep going after a sequence fails and report every result (default true). false stops at the first failure'),
  killChromeOnFinish: z.boolean().optional().describe("run/runAll: after finishing (skipped on pause/abort), kill the browsers this run owns - its own connection plus any a launch step actually created. A step that reached an already-bound reference only borrowed that browser and it is left running, so an instance you launched yourself survives. Also skipped for any browser whose port another live connection shares (a launch step usually opens a tab in the same instance), and the run reports which connection kept it alive. On runAll only the LAST sequence carries it, so a preamble's browser survives between sequences and a suite that stops early leaves the browsers up."),
}).strict();

export type ReplayArgs = z.infer<typeof replaySchema>;
