/**
 * The `replay` tool's parameters, and the arguments type every action handler takes.
 */
import { z } from 'zod';

export const replaySchema = z.object({
  action: z.enum([
    'history', 'create', 'list', 'get', 'delete',
    'export', 'load', 'listSaved', 'deleteSaved',
    'run', 'runAll', 'step', 'finish', 'insert', 'addCheck', 'declare', 'status', 'cancel',
    'repeat', 'runFromLog',
    'recordInteraction'
  ]),
  limit: z.number().optional().describe('Max items (default:50)'),
  name: z.string().optional(),
  description: z.string().optional(),
  expectedOutcome: z.string().optional(),
  startUrl: z.string().optional().describe('create: sequence start URL. run: replaces the stored startUrl for this run only'),
  envFile: z.string().optional().describe('run/runAll: KEY=value file supplying the {{env:NAME}} tokens; its values win over the server environment'),
  baseUrl: z.string().optional().describe('run/runAll: origin every absolute URL in the run moves onto, path and query kept'),
  indices: z.array(z.number()).optional().describe('Command indices'),
  params: z.record(z.any()).optional().describe('repeat, one index: fields replacing the recorded ones; null removes one'),
  lines: z.array(z.number()).optional().describe('Log line numbers'),
  sequenceId: z.string().optional(),
  runId: z.string().optional().describe('status/cancel: the background run, by the id run returned'),
  bench: z.boolean().optional().describe('run: play in the bench open on connectionReason, as its Replay button does, so it shows there'),
  wait: z.boolean().optional().describe('run: block until the run completes and return the full result. Default false: return a runId at once'),
  global: z.boolean().optional().describe('Use ~/.devharness/'),
  format: z.enum(['sequence', 'playwright', 'puppeteer']).optional(),
  filename: z.string().optional(),
  intoHistory: z.boolean().optional(),
  connectionReason: z.string().optional(),
  requiredConnections: z.array(z.object({
    reference: z.string().describe('Reference the steps use, e.g. "duo-member-two"'),
    profile: z.string().optional().describe('Named persistent Chrome profile to come up on'),
    url: z.string().optional().describe("Opened on launch (defaults to the sequence's startUrl)"),
    role: z.string().optional().describe('Why this browser exists, shown in the run summary'),
    forceNewInstance: z.boolean().optional().describe('A distinct process rather than a tab (default true; false with profile)'),
  }).strict()).optional().describe('declare: the browsers this sequence needs. Replaces the whole list; [] clears it'),
  tags: z.array(z.string()).optional().describe("declare: kinds of sequence, e.g. ['ui'], replacing the list. runAll: run only sequences carrying one of these"),
  requiredSockets: z.array(z.string()).optional().describe("declare: URL substrings of the WebSockets its assertions ride on, e.g. ['/api/sync/socket'], replacing the list"),
  connections: z.record(z.string()).optional().describe('run: { "<recorded reference>": "<reference here>" }, rebinding a multi-connection sequence onto this session'),
  record: z.boolean().optional(),
  variables: z.record(z.string()).optional().describe('run/runAll: replacement text for recorded typed-text steps, keyed var_<0-based step>_<selector with non-alphanumerics as _>'),
  stepTimeout: z.number().optional().describe('Per-step ms (default 30000)'),
  totalTimeout: z.number().optional().describe('Total ms'),
  startFrom: z.number().optional().describe('Start step (1-indexed)'),
  stepTo: z.number().optional().describe('Pause after step'),
  stepCount: z.number().optional().describe('Steps to run'),
  insertIndices: z.array(z.number()).optional(),
  insertAfterStep: z.number().optional(),
  check: z.record(z.any()).optional().describe("addCheck: the check step's parameters as the check tool takes them, holds/fails included"),
  comment: z.string().optional().describe('addCheck: note stored on the step'),
  overwrite: z.boolean().optional(),
  newName: z.string().optional(),
  showOverlay: z.boolean().optional(),
  closeTabOnDone: z.boolean().optional()
    .describe('recordInteraction: whether finishing closes the tab (default:true). False leaves a tab the person was already working in'),
  simplifyEvents: z.boolean().optional().describe('recordInteraction: collapse noisy raw events (default:true)'),
  includeHovers: z.boolean().optional().describe('recordInteraction: keep mousemove steps (default:false)'),
  outputFormat: z.enum(['events', 'commands', 'review', 'puppeteer', 'playwright']).optional()
    .describe('get: commands|playwright|puppeteer. recordInteraction: events|commands (JSON) or review (readable walkthrough), appended to the summary'),
  preferCoordinates: z.boolean().optional().describe('recordInteraction: emit x,y clicks instead of selectors (default:false)'),
  preferSelectors: z.boolean().optional().describe('recordInteraction: emit selector clicks even for canvas; wins over preferCoordinates (default:false)'),
  issueId: z.number().optional(),
  issueType: z.enum(['bug', 'feature']).optional(),
  issueTitle: z.string().optional(),
  showReplayOverlay: z.boolean().optional(),
  showAll: z.boolean().optional().describe('Show all sequences including completed/fixed issues'),
  requireSockets: z.boolean().optional().describe('run/runAll: fail the run when a WebSocket closes or errors during it'),
  strict: z.enum(['errors', 'warnings']).optional().describe("run/runAll: fail the run on console output it produces - 'errors', or 'warnings' for errors and warnings"),
  folder: z.string().optional().describe("runAll: sequences subfolder to run; omitted, every folder not starting with '_'"),
  continueOnFailure: z.boolean().optional().describe('runAll: keep going after a sequence fails (default true)'),
  killChromeOnFinish: z.boolean().optional().describe('run/runAll: kill the browsers this run launched once it finishes'),
}).strict();

export type ReplayArgs = z.infer<typeof replaySchema>;
